version: "3.6"
services:
    mongo:
        container_name: openresty
        image: openresty/openresty:1.17.8.2-2-alpine-fat
        restart: on-failure
        volumes: 
            - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - /home/alfa/Playground/Openresty/lua-cutom-ssl-termination/certs/idads.my.id:/etc/ssl/certs/idads.my.id
            - /home/alfa/Project/Website-builder-V2:/var/www/html/Website-builder-V2
            - /run/php/php7.4-fpm.sock:/run/php/php7.4-fpm.sock
        ports: 
            - 80:80
            - 443:443
            - 8000:8000
        

    